version: '3.9'
services:
  web:
    build: 
      context: .
    restart: always
    command: npm run start
    volumes:
      - .:/src
    ports:
      - "3001:3001"
#     depends_on:
#       - "db-mysql"
#     environment:
#       DB_HOST: 'db-mysql'
#       DB_PORT: '3306'

#   db-mysql:
#     image: mysql
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'db-schedula'
#       MYSQL_USER: 'schedula-user'
#       MYSQL_PASSWORD: 'password'
#       MYSQL_ROOT_PASSWORD: 'password'
#     ports:
#       - '3308:3306'
#     expose:
#       - '3308'
#     volumes:
#       - my-db:/var/lib/mysql
# volumes:
#   my-db:
